'use client';

import React, { useState, useMemo } from 'react';
import Link from 'next/link';
import {
  ClipboardList,
  Search,
  Filter,
  CheckCircle2,
  Clock,
  AlertCircle,
  ExternalLink,
  RotateCcw,
  UserCheck,
} from 'lucide-react';
import { RequestStatusBadge } from '@/components/ui/Badge';
import { MOCK_REQUESTS } from '@/lib/mock/logivoice-data';
import { formatDateTime } from '@/lib/utils';
import { Drawer } from '@/components/ui/Drawer';
import { EmptyState } from '@/components/ui/EmptyState';
import { OperationsRequest, RequestStatus, RequestType } from '@/types/logivoice';

export default function RequestsPage() {
  const [requests, setRequests] = useState<OperationsRequest[]>(MOCK_REQUESTS);
  const [activeTab, setActiveTab] = useState<'ALL' | 'BOOKING_REQUEST' | 'SUPPORT_TICKET' | 'CALLBACK_REQUEST'>('ALL');
  const [statusFilter, setStatusFilter] = useState<string>('ALL');
  const [searchQuery, setSearchQuery] = useState('');
  const [inspectReq, setInspectReq] = useState<OperationsRequest | null>(null);

  const filteredRequests = useMemo(() => {
    return requests.filter((req) => {
      const matchesTab = activeTab === 'ALL' || req.type === activeTab;
      const matchesStatus = statusFilter === 'ALL' || req.status === statusFilter;
      const q = searchQuery.toLowerCase();
      const matchesSearch =
        !searchQuery ||
        req.reference_no.toLowerCase().includes(q) ||
        req.customer_name.toLowerCase().includes(q) ||
        req.customer_phone.toLowerCase().includes(q) ||
        req.summary.toLowerCase().includes(q);

      return matchesTab && matchesStatus && matchesSearch;
    });
  }, [requests, activeTab, statusFilter, searchQuery]);

  const handleUpdateStatus = (reqId: string, newStatus: RequestStatus) => {
    setRequests((prev) =>
      prev.map((r) => (r.id === reqId ? { ...r, status: newStatus, updated_at: new Date().toISOString() } : r))
    );
    if (inspectReq && inspectReq.id === reqId) {
      setInspectReq({ ...inspectReq, status: newStatus, updated_at: new Date().toISOString() });
    }
  };

  return (
    <div className="space-y-6 min-w-0 max-w-full">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 dark:border-slate-800/80 pb-4">
        <div>
          <h1 className="text-xl font-bold text-slate-900 dark:text-white tracking-tight">Operations Requests &amp; Tickets</h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Bookings, customer support requests, and dispatcher callbacks generated by voice AI
          </p>
        </div>
        <div className="text-xs text-slate-500 dark:text-slate-400">
          Showing <span className="text-slate-900 dark:text-white font-semibold">{filteredRequests.length}</span> active tasks
        </div>
      </div>

      {/* Tabs */}
      <div className="flex items-center gap-2 border-b border-slate-200 dark:border-slate-800 pb-2 overflow-x-auto">
        <button
          onClick={() => setActiveTab('ALL')}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors shrink-0 ${
            activeTab === 'ALL'
              ? 'bg-sky-600 text-white shadow-xs'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-900'
          }`}
        >
          All Requests ({requests.length})
        </button>
        <button
          onClick={() => setActiveTab('BOOKING_REQUEST')}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors shrink-0 ${
            activeTab === 'BOOKING_REQUEST'
              ? 'bg-sky-600 text-white shadow-xs'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-900'
          }`}
        >
          Booking Requests ({requests.filter((r) => r.type === 'BOOKING_REQUEST').length})
        </button>
        <button
          onClick={() => setActiveTab('SUPPORT_TICKET')}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors shrink-0 ${
            activeTab === 'SUPPORT_TICKET'
              ? 'bg-sky-600 text-white shadow-xs'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-900'
          }`}
        >
          Support Tickets ({requests.filter((r) => r.type === 'SUPPORT_TICKET').length})
        </button>
        <button
          onClick={() => setActiveTab('CALLBACK_REQUEST')}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors shrink-0 ${
            activeTab === 'CALLBACK_REQUEST'
              ? 'bg-sky-600 text-white shadow-xs'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-900'
          }`}
        >
          Callbacks ({requests.filter((r) => r.type === 'CALLBACK_REQUEST').length})
        </button>
      </div>

      {/* Search & Filter Controls */}
      <div className="p-4 rounded-xl bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 shadow-xs flex flex-col md:flex-row items-stretch md:items-center gap-3">
        <div className="flex-1 relative">
          <Search className="w-4 h-4 text-slate-400 dark:text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search by reference, customer name, phone, or issue description..."
            className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-800 rounded-lg pl-9 pr-4 py-1.5 text-xs text-slate-900 dark:text-slate-200 placeholder-slate-400 dark:placeholder-slate-500 focus:outline-hidden focus:border-sky-500"
          />
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-500 dark:text-slate-400 shrink-0">Status:</span>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-800 rounded-lg px-2.5 py-1.5 text-xs text-slate-900 dark:text-slate-200 focus:outline-hidden focus:border-sky-500"
          >
            <option value="ALL">All Statuses</option>
            <option value="PENDING">Pending</option>
            <option value="CONFIRMED">Confirmed</option>
            <option value="IN_REVIEW">In Review</option>
            <option value="COMPLETED">Completed</option>
            <option value="REJECTED">Rejected</option>
          </select>
        </div>
      </div>

      {/* Table */}
      {filteredRequests.length === 0 ? (
        <EmptyState
          title="No operations requests found"
          description="Try changing the tab filter or search query."
          actionLabel="Clear Filters"
          onAction={() => {
            setActiveTab('ALL');
            setStatusFilter('ALL');
            setSearchQuery('');
          }}
        />
      ) : (
        <div className="table-container bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 shadow-xs">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="border-b border-slate-200 dark:border-slate-800 bg-slate-100/80 dark:bg-slate-950/80 text-slate-600 dark:text-slate-400 uppercase text-[11px] tracking-wider">
                <th className="py-3 px-4">Ref #</th>
                <th className="py-3 px-4">Type</th>
                <th className="py-3 px-4">Customer</th>
                <th className="py-3 px-4">Summary</th>
                <th className="py-3 px-4">Priority</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4">Assigned To</th>
                <th className="py-3 px-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 dark:divide-slate-800/60">
              {filteredRequests.map((req) => (
                <tr key={req.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/30 transition-colors">
                  <td className="py-3 px-4 font-mono font-bold text-sky-600 dark:text-sky-400">
                    {req.reference_no}
                    <span className="block text-[10px] text-slate-500 font-normal">
                      {formatDateTime(req.created_at)}
                    </span>
                  </td>
                  <td className="py-3 px-4">
                    <span className="px-2 py-0.5 rounded-md bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 text-[11px] font-medium border border-slate-200 dark:border-slate-700">
                      {req.type.replace('_', ' ')}
                    </span>
                  </td>
                  <td className="py-3 px-4">
                    <div className="font-medium text-slate-900 dark:text-white">{req.customer_name}</div>
                    <div className="text-[11px] font-mono text-slate-500 dark:text-slate-400">{req.customer_phone}</div>
                  </td>
                  <td className="py-3 px-4 max-w-sm">
                    <p className="text-slate-700 dark:text-slate-200 line-clamp-2">{req.summary}</p>
                  </td>
                  <td className="py-3 px-4">
                    <span
                      className={`text-[10px] font-bold px-1.5 py-0.5 rounded border uppercase ${
                        req.priority === 'URGENT'
                          ? 'bg-rose-50 dark:bg-rose-950/80 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800'
                          : req.priority === 'HIGH'
                          ? 'bg-amber-50 dark:bg-amber-950/80 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800'
                          : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 border-slate-200 dark:border-slate-700'
                      }`}
                    >
                      {req.priority}
                    </span>
                  </td>
                  <td className="py-3 px-4">
                    <RequestStatusBadge status={req.status} />
                  </td>
                  <td className="py-3 px-4 text-slate-700 dark:text-slate-300">
                    <div className="flex items-center gap-1.5">
                      <UserCheck className="w-3.5 h-3.5 text-slate-400" />
                      <span>{req.assigned_to || 'Unassigned'}</span>
                    </div>
                  </td>
                  <td className="py-3 px-4 text-right">
                    <button
                      onClick={() => setInspectReq(req)}
                      className="px-2.5 py-1 rounded-md bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-sky-600 dark:text-sky-400 text-xs font-medium transition-colors border border-slate-300 dark:border-slate-700"
                    >
                      Inspect
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Request Inspection Drawer */}
      <Drawer
        isOpen={!!inspectReq}
        onClose={() => setInspectReq(null)}
        title={`Request Investigation — ${inspectReq?.reference_no}`}
        subtitle={`Type: ${inspectReq?.type} • Customer: ${inspectReq?.customer_name}`}
      >
        {inspectReq && (
          <div className="space-y-6 text-xs">
            {/* Status & Priority */}
            <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-slate-500 dark:text-slate-400 font-medium">Current Status</span>
                <RequestStatusBadge status={inspectReq.status} />
              </div>
              <div className="flex justify-between items-center">
                <span className="text-slate-500 dark:text-slate-400 font-medium">Priority Level</span>
                <span className="font-bold text-amber-600 dark:text-amber-300">{inspectReq.priority}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-slate-500 dark:text-slate-400 font-medium">Assigned Dispatcher</span>
                <span className="text-slate-900 dark:text-white font-medium">{inspectReq.assigned_to}</span>
              </div>
            </div>

            {/* Requirement Summary */}
            <div className="space-y-1.5">
              <h3 className="font-semibold text-slate-900 dark:text-white uppercase text-[11px] tracking-wider">Requirement Summary</h3>
              <p className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 text-slate-800 dark:text-slate-300 leading-relaxed">
                {inspectReq.summary}
              </p>
            </div>

            {/* Structured Details Payload */}
            <div className="space-y-1.5 min-w-0 max-w-full">
              <h3 className="font-semibold text-slate-900 dark:text-white uppercase text-[11px] tracking-wider">Operational Payload</h3>
              <div className="p-3.5 rounded-xl bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 font-mono text-[11px] space-y-1.5 min-w-0 max-w-full overflow-hidden">
                {Object.entries(inspectReq.details).map(([key, value]) => (
                  <div key={key} className="flex justify-between items-baseline gap-2 min-w-0">
                    <span className="text-slate-500 capitalize shrink-0">{key.replace('_', ' ')}:</span>
                    <span className="text-slate-900 dark:text-slate-200 break-all text-right font-mono">{String(value)}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Workflow Status Actions */}
            <div className="space-y-2 pt-2 border-t border-slate-200 dark:border-slate-800">
              <h3 className="font-semibold text-slate-900 dark:text-white uppercase text-[11px] tracking-wider">Update Dispatcher Status</h3>
              <div className="grid grid-cols-2 gap-2">
                <button
                  onClick={() => handleUpdateStatus(inspectReq.id, 'CONFIRMED')}
                  className="py-2 px-3 rounded-lg bg-emerald-50 dark:bg-emerald-600/20 hover:bg-emerald-100 dark:hover:bg-emerald-600/30 text-emerald-700 dark:text-emerald-300 border border-emerald-300 dark:border-emerald-500/30 font-medium transition-colors"
                >
                  Mark Confirmed
                </button>
                <button
                  onClick={() => handleUpdateStatus(inspectReq.id, 'IN_REVIEW')}
                  className="py-2 px-3 rounded-lg bg-amber-50 dark:bg-amber-600/20 hover:bg-amber-100 dark:hover:bg-amber-600/30 text-amber-700 dark:text-amber-300 border border-amber-300 dark:border-amber-500/30 font-medium transition-colors"
                >
                  Mark In Review
                </button>
                <button
                  onClick={() => handleUpdateStatus(inspectReq.id, 'COMPLETED')}
                  className="py-2 px-3 rounded-lg bg-sky-50 dark:bg-sky-600/20 hover:bg-sky-100 dark:hover:bg-sky-600/30 text-sky-700 dark:text-sky-300 border border-sky-300 dark:border-sky-500/30 font-medium transition-colors"
                >
                  Mark Completed
                </button>
                <button
                  onClick={() => handleUpdateStatus(inspectReq.id, 'REJECTED')}
                  className="py-2 px-3 rounded-lg bg-rose-50 dark:bg-rose-600/20 hover:bg-rose-100 dark:hover:bg-rose-600/30 text-rose-700 dark:text-rose-300 border border-rose-300 dark:border-rose-500/30 font-medium transition-colors"
                >
                  Mark Rejected
                </button>
              </div>
            </div>

            {/* Link to Source Call */}
            <div className="pt-2">
              <Link
                href={`/admin/calls/${inspectReq.call_id}`}
                className="w-full py-2.5 px-4 rounded-lg bg-white dark:bg-slate-900 hover:bg-slate-50 dark:hover:bg-slate-800 text-sky-600 dark:text-sky-400 border border-slate-200 dark:border-slate-800 font-semibold text-center block transition-colors shadow-xs"
              >
                Inspect Source Call Voice Transcript &rarr;
              </Link>
            </div>
          </div>
        )}
      </Drawer>
    </div>
  );
}
